trigger:
  branches:
    include:
      - main
  paths:
    include:
      - Shopping/Shopping.Client/*
      - aks/shoppingclient.yaml

resources:
  - repo: self

variables:
  imageRepository: 'venkatabhupathi/shoppingclient'
  dockerfilePath: 'Shopping/Shopping.Client/Dockerfile'
  tag: 'latest-$(Build.BuildId)'
  imagePullSecret: 'dockerhub-secret'
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build stage
  jobs:
    - job: Build
      displayName: Build
      pool:
        vmImage: $(vmImageName)
      steps:
        - task: Docker@2
          displayName: Build and push an image to Docker Hub
          inputs:
            command: buildAndPush
            repository: $(imageRepository)
            dockerfile: $(dockerfilePath)
            containerRegistry: 'Docker Hub'
            buildContext: $(Build.SourcesDirectory)/Shopping
            tags: |
              $(tag)
        - upload: aks
          artifact: aks

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  jobs:
    - deployment: Deploy
      displayName: Deploy Shopping Client
      pool:
        vmImage: $(vmImageName)
      environment: 'aspnetrunrundevops.default'
      strategy:
        runOnce:
          deploy:
            steps:
            - task: KubernetesManifest@0
              displayName: Create imagePullSecret
              inputs:
                action: createSecret
                secretName: $(imagePullSecret)
                dockerRegistryEndpoint: 'Docker Hub'
            - task: KubernetesManifest@0
              displayName: Deploy Shopping Client to Kubernetes cluster
              inputs:
                action: deploy
                manifests: |
                  $(Pipeline.Workspace)/aks/shoppingclient.yaml
                imagePullSecrets: |
                  $(imagePullSecret)
                containers: |
                  $(imageRepository):$(tag)
