services:
  shopping-api:
    build:
      context: .
      dockerfile: Shopping.API/Dockerfile
    image: ${DOCKER_REGISTRY-}shopping-api
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
      - MongoDBConnectionString=mongodb://shopping.db:27017
    depends_on:
      - shopping.db

  shopping-client:
    build:
      context: .
      dockerfile: Shopping.Client/Dockerfile
    image: ${DOCKER_REGISTRY-}shopping-client
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ShoppingAPIUrl=http://shopping-api
    depends_on:
      - shopping-api

  shopping.db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - shopping-db-data:/data/db

volumes:
  shopping-db-data:
